syntax = "proto3";
option java_package = "com.nowcent.ham.pb";
option java_multiple_files = true;
option go_package = "pb/ham";
import "common.proto";

message GetCourseScoreItemRequest {
  optional string id = 1;
  optional string course_name = 2;
  optional string instructor = 3;
  repeated CourseScoreRangeRequestItem range = 4;
}

message GetCourseScoreItemResponse {
  CourseScoreItem item = 1;
}

message CourseScoreItem {
  string name = 1;
  string instructor = 2;
  double average = 3;
  int32 total = 4;
  repeated CourseScoreRangeResponseItem range = 5;
  string id = 6;
}

message CourseScoreRangeRequestItem {
  int32 from = 1;
  int32 to = 2;
}

message CourseScoreRangeResponseItem {
  int32 from = 1;
  int32 to = 2;
  int32 total = 3;
  string color = 4;
}

service GetCourseScoreService {
  rpc GetCourseScoreItem(GetCourseScoreItemRequest) returns (GetCourseScoreItemResponse);
}

message UploadScoreRequest {
  string student_id_secret = 1;
  repeated UploadScoreItem score = 2;
}

message UploadScoreResponse {}

message UploadScoreItem {
  string name = 1;
  string instructor = 2;
  string courseId = 3;
  double credit = 4;
  int32 year = 5;
  int32 semester = 6;
  int32 score = 7;
}

service UploadScoreService {
  rpc UploadScore (UploadScoreRequest) returns (UploadScoreResponse) {}
}
